CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS well_header (
    base_uwi text,
    import_timestamp text,
    raw_id bigint,
    source_file text,
    suffix text,
    user_format_well_id text,
    area text,
    well_name text,

    cur_operator_code text,
    cur_operator_name text,
    lahee_class_code text,
    lic_subs_well_obj text,
    lic_wa_wid_permit text,
    org_operator_name text,
    orig_operator_code text,
    orig_units_m_api text,
    well_pad_id text,
    well_type text,
    "Permit_id" text
);

CREATE UNIQUE INDEX IF NOT EXISTS well_header_base_uwi_unique_idx ON well_header (base_uwi);

CREATE TABLE IF NOT EXISTS well_location (
    raw_id bigint PRIMARY KEY,
    base_uwi text,
    import_timestamp text,
    source_file text,
    suffix text,
    user_format_well_id text,
    bot_hole_latitude_nad83 text,
    bot_hole_longitude_nad83 text,
    govt_surf_loc text,
    latitude double precision,
    longitude double precision,
    surf_hole_latitude_nad83 text,
    surf_hole_longitude_nad83 text,
    surf_loc text
);
CREATE INDEX IF NOT EXISTS well_location_base_uwi_idx ON well_location (base_uwi);

CREATE TABLE IF NOT EXISTS well_status (
    raw_id bigint PRIMARY KEY,
    base_uwi text,
    import_timestamp text,
    source_file text,
    suffix text,
    user_format_well_id text,
    cur_operator_code text,
    cur_operator_name text,
    lahee_class_code text,
    lic_subs_well_obj text,
    lic_wa_wid_permit text,
    org_operator_name text,
    orig_operator_code text,
    orig_units_m_api text,
    well_pad_id text,
    well_type text,
    "Permit_id" text,
    inactive_well boolean,
    shut_in_well boolean,
    well_status_abrv text,
    well_status_text text
);
CREATE INDEX IF NOT EXISTS well_status_base_uwi_idx ON well_status (base_uwi);

CREATE TABLE IF NOT EXISTS well_drilling (
    raw_id bigint PRIMARY KEY,
    base_uwi text,
    import_timestamp text,
    source_file text,
    suffix text,
    user_format_well_id text,
    date_drlg_completed date,
    date_rig_released date,
    date_well_spudded date,
    drilling_contractor text,
    drilling_rig_number text,
    md_all_wells_m double precision,
    md_deviated_wells_m double precision,
    tvd_m double precision
);
CREATE INDEX IF NOT EXISTS well_drilling_base_uwi_idx ON well_drilling (base_uwi);

CREATE TABLE IF NOT EXISTS well_casing (
    raw_id bigint PRIMARY KEY,
    base_uwi text,
    import_timestamp text,
    source_file text,
    suffix text,
    user_format_well_id text,
    casing_depth_m double precision,
    casing_grade text,
    casing_latitude double precision,
    casing_location text,
    casing_longitude double precision,
    casing_remarks text,
    casing_size_mm double precision,
    casing_weight_kg_m double precision,
    casing_type text
);
CREATE INDEX IF NOT EXISTS well_casing_base_uwi_idx ON well_casing (base_uwi);

CREATE TABLE IF NOT EXISTS well_production_summary (
    raw_id bigint PRIMARY KEY,
    base_uwi text,
    import_timestamp text,
    source_file text,
    suffix text,
    user_format_well_id text,
    prod_status_abrv text,
    prod_status_text text,
    prod_inject_frmtn text,
    on_inject_yyyy_mm_dd date,
    on_prod_yyyy_mm_dd date,
    first_inject_yyyy_mm text,
    first_prod_yyyy_mm text,
    last_inject_yyyy_mm text,
    last_prod_yyyy_mm text,
    most_recent_12_mo_total_gas_e3m3 double precision,
    most_recent_12_mo_total_oil_m3 double precision,
    most_recent_12_mo_total_wtr_m3 double precision,
    total_production_hrs double precision
);
CREATE INDEX IF NOT EXISTS well_production_summary_base_uwi_idx ON well_production_summary (base_uwi);

CREATE TABLE IF NOT EXISTS wellstor_all (
    raw_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file text,
    import_timestamp text,
    user_format_well_id text,
    area text,
    well_status_text text,
    prod_status_text text,
    surf_hole_latitude_nad83 text,
    surf_hole_longitude_nad83 text,
    uwi_base text,
    uwi_suffix text,
    deepest_casing_depth text,
    deepest_casing_size text,
    deepest_casing_grade text,
    deepest_casing_weight text,
    max_casing_volume_m3 text,
    available_wellbore_volume_m3 text,
    normalized_wellstor_volume_m3 text,
    orphan text,
    wellstor_flag text
);
